name: servizo_vendor
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.7.2
  flutter_easyloading: ^3.0.5
  http: ^1.2.2
  shared_preferences: ^2.2.3
  firebase_core: ^3.4.0
  animated_text_kit: ^4.2.3
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.1
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.19.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  local_auth: ^2.3.0
  flutter_image_compress: ^2.3.0
  mailer: ^6.4.1
  shimmer: ^3.0.0
  cupertino_calendar_picker: ^2.2.5
  cached_network_image: ^3.4.1
  iconsax: ^0.0.8
  lottie: ^3.3.1
  visibility_detector: ^0.4.0+2
  syncfusion_flutter_pdf: ^31.1.18
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  share_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/icons/
    - assets/banner/
    - assets/iutils/
    - assets/animations/
    - assets/onboard/